apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
  namespace: poste-01
spec:
  # Servizio di replica
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  # template del pod
  template:
    metadata:
      labels:
        app: nginx
        env: prod
        type: proxy    
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
