# Il token generato nel passaggio precedente viene
# salvato come secret in kube col nome "admin-user"
apiVersion: v1
kind: Secret
metadata:
  name: admin-user-secret
  #namespace: kubernetes-dashboard
  namespace: default
  annotations:
    kubernetes.io/service-account.name: "admin-user"
type: kubernetes.io/service-account-token