apiVersion: v1
kind: Pod
metadata:
  name: webapp
  namespace: poste-01
spec:
  volumes:
  - name: logs-volume
    emptyDir:
      medium: Memory
      sizeLimit: 128Mi
  containers:
  - name: webapp
    image: nginx
    volumeMounts:
    - name: logs-volume
      mountPath: /var/log/nginx
  - name : sidecar
    image: busybox
    command: ["/bin/sh", "-c", "while true; do date >> /logs/test.log; sleep 5; done"]
    volumeMounts:
    - name: logs-volume
      mountPath: /logs