apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
  namespace: poste-01
data:
  APP_COLOR: "blue"
  USER_MODE: "production"
  APP_VERSION: "1.0.0"
  config.json: |
    {
      "APP_COLOR": "blue",
      "APP_MODE": "production",
      "APP_VERSION": "1.0.0"
    }
  test.conf: |
    [settings]
    APP_COLOR=blue
    APP_MODE=production
    APP_VERSION=1.0.0
  config.yaml: |
    APP_COLOR: blue
    APP_MODE: production
    APP_VERSION: 1.0.0
  test.ini: |
    [settings]
    APP_COLOR=blue
    APP_MODE=production
    APP_VERSION=1.0.0
  app.properties: |
    APP_COLOR=blue
    APP_MODE=production
    APP_VERSION=1.0.0

---

apiVersion: v1
kind: Secret
metadata:
  name: webapp-secret
  namespace: poste-01
type: Opaque
stringData:
  DB_USER: admin
  DB_PASSWORD: P@ssw0rd
  API_KEY: 12345-ABCDE

---
apiVersion: v1
kind: Pod
metadata:
  name: webapp
  namespace: poste-01
spec:
  volumes:
  - name: logs-volume
    emptyDir: {}
  - name: config-volume
    configMap:
      name: webapp-config
  - name: secret-volume
    secret:
      secretName: webapp-secret
  containers:
  - name: webapp
    image: nginx
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: webapp-secret
          key: DB_USER
    volumeMounts:
    - name: logs-volume
      mountPath: /var/log/nginx
    - name: config-volume
      mountPath: /settings
    - name: secret-volume
      mountPath: /configs
      readOnly: true
  - name : sidecar
    image: busybox
    command: ["/bin/sh", "-c", "while true; do date >> /logs/test.log; sleep 5; done"]
    volumeMounts:
    - name: logs-volume
      mountPath: /logs