apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:2.4.57-alpine
        ports:
        - containerPort: 80
          protocol: TCP