apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-job-test
  namespace: poste-01
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cnt-do-something
            image: nginx
            args:
            - /bin/sh
            - -c
            - 'echo "Current Date: $(date)"'
          restartPolicy: OnFailure
