apiVersion: v1
kind: Pod
metadata:
  name: webapp2
  namespace: poste-01
spec:
  containers:
    - name: webapp
      image: nginx
      volumeMounts:
        - mountPath: /test
          name: webapp-storage 
  volumes:
    - name: webapp-storage
      persistentVolumeClaim:
        claimName: pvc-hostpath-default