apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
  namespace: poste-01
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.1
    path: /export/logs
  mountOptions:
    - hard
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs
  namespace: poste-01 
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Deployment
metadata:
  name: webapp-nfs
  namespace: poste-01 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp-nfs
  template:
    metadata:
      labels:
        app: webapp-nfs
    spec:
      containers:
        - name: webapp
          image: nginx
          volumeMounts:
            - mountPath: /test
              name: shared-storage
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: pvc-nfs