apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hostpath-default
  namespace: poste-01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

  # storageClassName: microk8s-hostpath

---

apiVersion: v1
kind: Pod
metadata:
  name: webapp
  namespace: poste-01
spec:
  containers:
    - name: webapp
      image: nginx
      volumeMounts:
        - mountPath: /test
          name: webapp-storage 
  volumes:
    - name: webapp-storage
      persistentVolumeClaim:
        claimName: pvc-hostpath-default